spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/MANGODB
    username: products
    password: products
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true