CREATE SEQUENCE PRODUCT_SEQUENCE
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE PRICE_SEQUENCE
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE PRODUCT
(
    ID          NUMBER(19, 0)      NOT NULL,
    NAME        VARCHAR2(255 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE PRICE
(
    ID         NUMBER(19, 0) NOT NULL,
    VALUE      NUMBER(12, 2) NOT NULL,
    INIT_DATE  DATE NOT NULL,
    END_DATE   DATE,
    PRODUCT_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT PK_PRICE PRIMARY KEY (ID),
    CONSTRAINT FK_PRICE_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE INDEX IDX_PRICE_PRODUCT_DATES
    ON PRICE (PRODUCT_ID, INIT_DATE, END_DATE);